import { EN } from './locales/en';
import { HI } from './locales/hi';

const dictionaryPairs = Object.entries(EN).map(([key, english]) => [english, HI[key] || english]);

export const UI_HI: Record<string, string> = Object.fromEntries([
  ...dictionaryPairs,
  ['SC Community Connect', 'एससी कम्युनिटी कनेक्ट'],
  ['SC Connect', 'एससी कनेक्ट'],
  ['Language', 'भाषा'],
  ['English', 'अंग्रेज़ी'],
  ['Top Achievers', 'शीर्ष उपलब्धि प्राप्तकर्ता'],
  ['Verified', 'सत्यापित'],
  ['Pending', 'लंबित'],
  ['Blocked', 'अवरुद्ध'],
  ['Optional', 'वैकल्पिक'],
  ['Close', 'बंद करें'],
  ['Cancel', 'रद्द करें'],
  ['Save', 'सहेजें'],
  ['Delete', 'हटाएं'],
  ['Edit', 'संपादित करें'],
  ['View', 'देखें'],
  ['Approve', 'स्वीकृत करें'],
  ['Reject', 'अस्वीकार करें'],
  ['Accept', 'स्वीकार करें'],
  ['Decline', 'अस्वीकार करें'],
  ['Retry', 'फिर प्रयास करें'],
  ['Active', 'सक्रिय'],
  ['History', 'इतिहास'],
  ['Open', 'खुला'],
  ['Closed', 'बंद'],
  ['Current', 'वर्तमान'],
  ['Legacy', 'विरासत'],
  ['All', 'सभी'],
  ['General', 'सामान्य'],
  ['Name', 'नाम'],
  ['Status', 'स्थिति'],
  ['Actions', 'कार्रवाइयां'],
  ['Role', 'भूमिका'],
  ['Summary', 'सारांश'],
  ['Description', 'विवरण'],
  ['Category', 'श्रेणी'],
  ['Achievement', 'उपलब्धि'],
  ['Education', 'शिक्षा'],
  ['Community', 'समुदाय'],
  ['Government', 'सरकार'],
  ['Business', 'व्यवसाय'],
  ['Technology', 'प्रौद्योगिकी'],
  ['Healthcare', 'स्वास्थ्य सेवा'],
  ['Judiciary', 'न्यायपालिका'],
  ['Law', 'कानून'],
  ['Music', 'संगीत'],
  ['Everyone', 'सभी सदस्य'],
  ['Doctors', 'चिकित्सक'],
  ['Engineers', 'इंजीनियर'],
  ['Social workers', 'सामाजिक कार्यकर्ता'],
  ['You', 'आप'],
  ['Live', 'लाइव'],
  ['Mobile', 'मोबाइल'],
  ['Email', 'ईमेल'],
  ['Share', 'साझा करें'],
  ['Copy', 'कॉपी करें'],
  ['Toggle navigation', 'नेविगेशन खोलें या बंद करें'],
  ['Open profile menu', 'प्रोफ़ाइल मेन्यू खोलें'],
  ['Log out', 'लॉग आउट'],
  ['Secure admin workspace', 'सुरक्षित प्रशासन कार्यक्षेत्र'],
  ['I can help with', 'मैं इन क्षेत्रों में सहायता कर सकता/सकती हूं'],
  ['Edit help fields', 'सहायता क्षेत्र बदलें'],
  ['Member privilege', 'सदस्य सुविधा'],
  ['Request an invite code', 'आमंत्रण कोड का अनुरोध करें'],
  ['Enter the email or mobile number of the person you want to invite. An administrator will review your request.', 'जिस व्यक्ति को आमंत्रित करना है उसका ईमेल या मोबाइल नंबर दर्ज करें। प्रशासक अनुरोध की समीक्षा करेगा।'],
  ['Request submitted', 'अनुरोध जमा हो गया'],
  ['Admin review pending', 'प्रशासक की समीक्षा लंबित'],
  ['is safely queued. This status updates automatically.', 'का अनुरोध सुरक्षित कतार में है। स्थिति स्वतः अपडेट होगी।'],
  ['Review complete', 'समीक्षा पूरी हुई'],
  ['Request not approved', 'अनुरोध स्वीकृत नहीं हुआ'],
  ['Make another request', 'दूसरा अनुरोध करें'],
  ['Approved by admin', 'प्रशासक द्वारा स्वीकृत'],
  ['Your invite is ready', 'आपका आमंत्रण तैयार है'],
  ['Request another code', 'दूसरा कोड मांगें'],
  ['Complete your member profile', 'अपनी सदस्य प्रोफ़ाइल पूरी करें'],
  ['How can you help the community?', 'आप समुदाय की किस प्रकार सहायता कर सकते हैं?'],
  ['Select the areas where members may approach you for guidance. Choose up to eight; only your field names will be shown.', 'वे क्षेत्र चुनें जिनमें सदस्य आपसे मार्गदर्शन ले सकते हैं। अधिकतम आठ चुनें; केवल क्षेत्रों के नाम दिखेंगे।'],
  ['Verified community network', 'सत्यापित सामुदायिक नेटवर्क'],
  ['Leadership, learning, public events and community voices in one trusted place.', 'नेतृत्व, शिक्षा, सार्वजनिक कार्यक्रम और समुदाय की आवाज़—एक विश्वसनीय मंच पर।'],
  ['Join the community', 'समुदाय से जुड़ें'],
  ['Open library', 'पुस्तकालय खोलें'],
  ['Leadership archive', 'नेतृत्व अभिलेख'],
  ['People who shaped public life', 'जनजीवन को दिशा देने वाले व्यक्तित्व'],
  ['Explore their work, departments, contributions and community perspectives.', 'उनके कार्य, विभाग, योगदान और सामुदायिक दृष्टिकोण जानें।'],
  ['Read contribution and blogs', 'योगदान और लेख पढ़ें'],
  ['View all leadership profiles', 'सभी नेतृत्व प्रोफ़ाइल देखें'],
  ['Community journal', 'सामुदायिक पत्रिका'],
  ['Ideas worth carrying forward', 'आगे बढ़ाने योग्य विचार'],
  ['Short editorial readings on constitutional values, representation, education and public service.', 'संवैधानिक मूल्यों, प्रतिनिधित्व, शिक्षा और जनसेवा पर संक्षिप्त संपादकीय लेख।'],
  ['Featured perspective', 'विशेष दृष्टिकोण'],
  ['Read article', 'लेख पढ़ें'],
  ['More readings', 'और लेख'],
  ['Events and notices', 'कार्यक्रम और सूचनाएं'],
  ['Meet, learn and participate', 'मिलें, सीखें और भाग लें'],
  ['Current dates and verified community announcements published by the admin team.', 'प्रशासन टीम द्वारा प्रकाशित वर्तमान तिथियां और सत्यापित सामुदायिक घोषणाएं।'],
  ['Full calendar', 'पूरा कैलेंडर'],
  ['No upcoming event is scheduled.', 'अभी कोई आगामी कार्यक्रम निर्धारित नहीं है।'],
  ['Community gallery', 'सामुदायिक गैलरी'],
  ['Moments from the field', 'मैदान से यादगार पल'],
  ['Photos from workshops, meetings and public events.', 'कार्यशालाओं, बैठकों और सार्वजनिक कार्यक्रमों की तस्वीरें।'],
  ['Published event photos will appear here.', 'प्रकाशित कार्यक्रम तस्वीरें यहां दिखाई देंगी।'],
  ['Broadcast desk', 'प्रसारण कक्ष'],
  ['Live community conversations', 'लाइव सामुदायिक संवाद'],
  ['Podcasts and video sessions controlled from the admin broadcast desk.', 'प्रशासन प्रसारण कक्ष से संचालित पॉडकास्ट और वीडियो सत्र।'],
  ['Live audio', 'लाइव ऑडियो'],
  ['Open broadcast desk', 'प्रसारण कक्ष खोलें'],
  ['The next programme will appear here automatically.', 'अगला कार्यक्रम यहां स्वतः दिखाई देगा।'],
  ['Browse scheduled and completed podcasts and videos in the broadcast desk.', 'प्रसारण कक्ष में निर्धारित और पूर्ण पॉडकास्ट व वीडियो देखें।'],
  ['View programmes', 'कार्यक्रम देखें'],
  ['Notices and calendar', 'सूचनाएं और कैलेंडर'],
  ['What is happening', 'क्या हो रहा है'],
  ['Verified community announcements, upcoming programmes and registration details in one clear calendar.', 'सत्यापित घोषणाएं, आगामी कार्यक्रम और पंजीकरण विवरण एक स्पष्ट कैलेंडर में।'],
  ['Upcoming events', 'आगामी कार्यक्रम'],
  ['Dates and venues are published by the community administrator.', 'तिथियां और स्थान समुदाय प्रशासक प्रकाशित करता है।'],
  ['Register', 'पंजीकरण करें'],
  ['No event has been scheduled yet.', 'अभी कोई कार्यक्रम निर्धारित नहीं है।'],
  ['Community notices', 'सामुदायिक सूचनाएं'],
  ['Important service, membership and safety updates.', 'सेवा, सदस्यता और सुरक्षा से जुड़े महत्वपूर्ण अपडेट।'],
  ['Community excellence', 'सामुदायिक उत्कृष्टता'],
  ['Top achievers', 'शीर्ष उपलब्धि प्राप्तकर्ता'],
  ['Discover accomplished people category-wise. Every profile is curated and published independently by the community administrator.', 'विभिन्न क्षेत्रों के सफल व्यक्तियों को श्रेणीवार देखें। हर प्रोफ़ाइल समुदाय प्रशासक द्वारा स्वतंत्र रूप से सत्यापित और प्रकाशित की जाती है।'],
  ['All fields', 'सभी क्षेत्र'],
  ['View reference', 'संदर्भ देखें'],
  ['Achiever profiles are being curated', 'उपलब्धि प्रोफ़ाइल तैयार की जा रही हैं'],
  ['Published profiles will appear here category-wise.', 'प्रकाशित प्रोफ़ाइल यहां श्रेणीवार दिखाई देंगी।'],
  ['People and public service', 'व्यक्तित्व और जनसेवा'],
  ['Explore selected leaders across generations, their areas of work, public contributions and short editorial readings.', 'विभिन्न पीढ़ियों के चुने हुए नेताओं, उनके कार्यक्षेत्र, सार्वजनिक योगदान और संपादकीय लेखों को जानें।'],
  ['Browse profiles', 'प्रोफ़ाइल देखें'],
  ['Scroll or use the arrow controls', 'स्क्रॉल करें या तीर बटन उपयोग करें'],
  ['View contribution', 'योगदान देखें'],
  ['No leader profile matches this search.', 'इस खोज से कोई नेतृत्व प्रोफ़ाइल नहीं मिली।'],
  ['Contribution index', 'योगदान सूची'],
  ['A quick view of the public work covered in this archive.', 'इस अभिलेख में शामिल सार्वजनिक कार्यों का संक्षिप्त विवरण।'],
  ['Profile articles', 'प्रोफ़ाइल लेख'],
  ['All leaders', 'सभी नेता'],
  ['Previous', 'पिछला'],
  ['Next', 'अगला'],
  ['Public contribution', 'सार्वजनिक योगदान'],
  ['Blogs and perspectives', 'लेख और दृष्टिकोण'],
  ['Short editorial readings on the ideas and public work connected to this profile.', 'इस प्रोफ़ाइल से जुड़े विचारों और सार्वजनिक कार्य पर संक्षिप्त संपादकीय लेख।'],
  ['Editorial note', 'संपादकीय टिप्पणी'],
  ['Community broadcast desk', 'सामुदायिक प्रसारण कक्ष'],
  ['Live conversations', 'लाइव संवाद'],
  ['Watch public video sessions and listen to podcasts published by the community administrator.', 'समुदाय प्रशासक द्वारा प्रकाशित सार्वजनिक वीडियो सत्र देखें और पॉडकास्ट सुनें।'],
  ['Playback status is controlled by the community admin.', 'प्लेबैक स्थिति समुदाय प्रशासक नियंत्रित करता है।'],
  ['Currently off air', 'अभी प्रसारण बंद है'],
  ['The next community broadcast will appear here.', 'अगला सामुदायिक प्रसारण यहां दिखाई देगा।'],
  ['This page checks for a new live podcast or video automatically every ten seconds.', 'यह पृष्ठ हर दस सेकंड में नया लाइव पॉडकास्ट या वीडियो स्वतः जांचता है।'],
  ['Scheduled, paused and completed programmes published by the admin.', 'प्रशासक द्वारा प्रकाशित निर्धारित, रोके गए और पूर्ण कार्यक्रम।'],
  ['No public broadcast has been published yet.', 'अभी कोई सार्वजनिक प्रसारण प्रकाशित नहीं हुआ है।'],

  // Authentication and visitor information
  ['Event photo carousel', 'कार्यक्रम तस्वीर स्लाइडर'],
  ['Sign-up progress', 'पंजीकरण प्रगति'],
  ['Show or hide password', 'पासवर्ड दिखाएं या छिपाएं'],
  ['Code provided by admin', 'प्रशासक द्वारा दिया गया कोड'],
  ['Password recovery progress', 'पासवर्ड पुनर्प्राप्ति प्रगति'],
  ['Community resources', 'सामुदायिक संसाधन'],
  ['Close resources', 'संसाधन बंद करें'],
  ['Community information', 'समुदाय की जानकारी'],
  ['Community leader spotlight', 'सामुदायिक नेता परिचय'],
  ['Previous leader', 'पिछला नेता'],
  ['Next leader', 'अगला नेता'],
  ['Scroll through community leaders', 'सामुदायिक नेताओं को स्क्रॉल करें'],
  ['Community principles', 'सामुदायिक सिद्धांत'],
  ['Library collection summary', 'पुस्तकालय संग्रह सारांश'],
  ['Community.', 'समुदाय।'],
  ['Knowledge.', 'ज्ञान।'],
  ['Opportunity.', 'अवसर।'],
  ['Photo: Wikimedia Commons', 'तस्वीर: विकिमीडिया कॉमन्स'],
  ['Back to login', 'लॉगिन पर वापस जाएं'],
  ['Full name is required.', 'पूरा नाम आवश्यक है।'],
  ['Community member', 'समुदाय सदस्य'],
  ['Doctor / Healthcare', 'चिकित्सक / स्वास्थ्य सेवा'],
  ['Engineer / Technology', 'इंजीनियर / प्रौद्योगिकी'],
  ['Social worker', 'सामाजिक कार्यकर्ता'],
  ['Where can you help the community?', 'आप समुदाय की सहायता किन क्षेत्रों में कर सकते हैं?'],
  ['Select one or more fields. You can update this later.', 'एक या अधिक क्षेत्र चुनें। आप इन्हें बाद में बदल सकते हैं।'],
  ['Required for login and recovery', 'लॉगिन और पुनर्प्राप्ति के लिए आवश्यक'],
  ['Enter a valid email address.', 'मान्य ईमेल पता दर्ज करें।'],
  ['Required for secure recovery', 'सुरक्षित पुनर्प्राप्ति के लिए आवश्यक'],
  ['Use 10-15 digits, optionally with country code.', 'देश कोड सहित या बिना 10–15 अंक दर्ज करें।'],
  ['Use 8+ characters with uppercase, lowercase, number and symbol.', 'कम से कम 8 अक्षर रखें, जिनमें बड़ा अक्षर, छोटा अक्षर, संख्या और चिन्ह हो।'],
  ['Passwords do not match.', 'पासवर्ड मेल नहीं खाते।'],
  ["Don't have an invite code?", 'आमंत्रण कोड नहीं है?'],
  ['Send a secure request to the admin. Keep this page open for automatic approval updates.', 'प्रशासक को सुरक्षित अनुरोध भेजें। स्वीकृति की स्वतः जानकारी के लिए यह पृष्ठ खुला रखें।'],
  ['Request pending', 'अनुरोध लंबित'],
  ['Waiting for admin approval. This status updates automatically.', 'प्रशासक की स्वीकृति की प्रतीक्षा है। स्थिति स्वतः अपडेट होगी।'],
  ['Request approved', 'अनुरोध स्वीकृत'],
  ['Your single-use code', 'आपका एक बार उपयोग होने वाला कोड'],
  ['has been added above.', 'ऊपर जोड़ दिया गया है।'],
  ['Approved', 'स्वीकृत'],
  ['Optional: upload the image/PDF to Google Drive, enable “Anyone with the link”, then paste its URL.', 'वैकल्पिक: तस्वीर/PDF को Google Drive पर अपलोड करें, “लिंक वाला कोई भी व्यक्ति” चालू करें और उसका URL यहां डालें।'],
  ['Enter a valid http(s) URL or leave this field empty.', 'मान्य http(s) URL डालें या यह क्षेत्र खाली छोड़ दें।'],
  ['ID proof (optional)', 'पहचान प्रमाण (वैकल्पिक)'],
  ['Enter the code generated for', 'इसके लिए बनाया गया कोड दर्ज करें'],
  ['Verification code', 'सत्यापन कोड'],
  ['Use different details', 'दूसरी जानकारी उपयोग करें'],
  ['New password', 'नया पासवर्ड'],
  ['Confirm new password', 'नया पासवर्ड दोबारा दर्ज करें'],
  ['About', 'हमारे बारे में'], ['Leaders', 'नेता'], ['Books', 'पुस्तकें'], ['Network', 'नेटवर्क'],
  ['Notices', 'सूचनाएं'], ['Help', 'सहायता'], ['Community voices', 'समुदाय की आवाज़'],
  ['Leadership that shaped equality.', 'समानता को आकार देने वाला नेतृत्व।'],
  ['About us', 'हमारे बारे में'],
  ['A trusted space for community progress.', 'सामुदायिक प्रगति के लिए एक विश्वसनीय मंच।'],
  ['SC Community Connect brings members together around education, constitutional awareness,', 'एससी कम्युनिटी कनेक्ट सदस्यों को शिक्षा, संवैधानिक जागरूकता,'],
  ['opportunity, public service and mutual support.', 'अवसर, जनसेवा और आपसी सहयोग के लिए जोड़ता है।'],
  ['Our purpose', 'हमारा उद्देश्य'],
  ['Make useful knowledge easier to reach, recognise people doing meaningful work and build', 'उपयोगी ज्ञान को सुलभ बनाना, सार्थक कार्य करने वालों को पहचान देना और'],
  ['respectful connections across professions and generations.', 'विभिन्न पेशों और पीढ़ियों के बीच सम्मानजनक संबंध बनाना।'],
  ['Learn', 'सीखें'], ['Connect', 'जुड़ें'], ['Contribute', 'योगदान दें'],
  ['Books, history and constitutional knowledge', 'पुस्तकें, इतिहास और संवैधानिक ज्ञान'],
  ['Members, social workers and organisations', 'सदस्य, सामाजिक कार्यकर्ता और संस्थाएं'],
  ['Respectful help, mentorship and public service', 'सम्मानजनक सहायता, मार्गदर्शन और जनसेवा'],
  ['SC reading room', 'एससी वाचनालय'],
  ['Read, learn and carry the ideas forward.', 'पढ़ें, सीखें और विचारों को आगे बढ़ाएं।'],
  ['Free PDFs', 'निःशुल्क PDF'], ['Publisher editions', 'प्रकाशक संस्करण'], ['Open shelf', 'संग्रह खोलें'],
  ['Free public reading', 'निःशुल्क सार्वजनिक पठन'],
  ['Official and institutional PDF sources', 'आधिकारिक और संस्थागत PDF स्रोत'],
  ['SC Digital Library', 'एससी डिजिटल पुस्तकालय'], ['Free PDF', 'निःशुल्क PDF'], ['Read PDF', 'PDF पढ़ें'],
  ['Reader issue?', 'पढ़ने में समस्या?'], ['Open official source', 'आधिकारिक स्रोत खोलें'],
  ['Bookstore shelf', 'पुस्तक विक्रेता संग्रह'], ['Printed and digital editions from publisher listings', 'प्रकाशक सूची के मुद्रित और डिजिटल संस्करण'],
  ['Paid edition', 'सशुल्क संस्करण'], ['View edition', 'संस्करण देखें'],
  ['Publisher prices shown for reference and may change on the linked store.', 'प्रकाशक की कीमतें केवल संदर्भ के लिए हैं और संबंधित स्टोर पर बदल सकती हैं।'],
  ['People and organisations', 'लोग और संस्थाएं'], ['Social action network', 'सामाजिक कार्य नेटवर्क'],
  ['NGOs and community organisations', 'गैर-सरकारी और सामुदायिक संस्थाएं'], ['Public notice board', 'सार्वजनिक सूचना पट्ट'],

  // Messaging and help lifecycle
  ['Verified member', 'सत्यापित सदस्य'], ['Write a message…', 'संदेश लिखें…'], ['Write a message', 'संदेश लिखें'],
  ['Send message', 'संदेश भेजें'], ['Messages', 'संदेश'], ['Choose a member', 'सदस्य चुनें'],
  ['No other verified members yet.', 'अभी कोई अन्य सत्यापित सदस्य नहीं है।'], ['Try again', 'फिर प्रयास करें'],
  ['Direct messages', 'सीधे संदेश'], ['Private conversations', 'निजी बातचीत'], ['Your conversations', 'आपकी बातचीत'],
  ['Select a member to start a secure conversation.', 'सुरक्षित बातचीत शुरू करने के लिए सदस्य चुनें।'], ['Send', 'भेजें'],
  ['Write a help message…', 'सहायता संदेश लिखें…'], ['Session · Private help conversation', 'सत्र · निजी सहायता बातचीत'],
  ['This help request has been closed. Reconnection is unavailable.', 'यह सहायता अनुरोध बंद हो चुका है। दोबारा जुड़ना उपलब्ध नहीं है।'],
  ['Request to Connect Again', 'दोबारा जुड़ने का अनुरोध करें'], ['View Related Post', 'संबंधित पोस्ट देखें'],
  ['End Conversation', 'बातचीत समाप्त करें'], ['Report', 'रिपोर्ट करें'], ['Block', 'अवरुद्ध करें'], ['Unblock', 'अवरोध हटाएं'],
  ['Help Messenger', 'सहायता संदेश'], ['Post-linked private conversations', 'पोस्ट से जुड़ी निजी बातचीत'],
  ['Reconnect requests', 'दोबारा जुड़ने के अनुरोध'], ['Recent notifications', 'हाल की सूचनाएं'],
  ['End this conversation?', 'क्या यह बातचीत समाप्त करनी है?'],
  ['This help conversation will be closed for both users and removed from Active chats. Previous messages will remain available in Chat History.', 'यह सहायता बातचीत दोनों सदस्यों के लिए बंद होकर सक्रिय चैट से हट जाएगी। पुराने संदेश चैट इतिहास में उपलब्ध रहेंगे।'],
  ['To talk again, a new contact request must be accepted.', 'दोबारा बात करने के लिए नया संपर्क अनुरोध स्वीकार होना आवश्यक है।'],
  ['This help request is no longer active.', 'यह सहायता अनुरोध अब सक्रिय नहीं है।'], ['Help Messages', 'सहायता संदेश'],
  ['Post closed', 'पोस्ट बंद'], ['Messaging blocked', 'संदेश सेवा अवरुद्ध'], ['Conversation ended', 'बातचीत समाप्त'],
  ['Reconnect request pending', 'दोबारा जुड़ने का अनुरोध लंबित'], ['Reconnect request received', 'दोबारा जुड़ने का अनुरोध मिला'],

  // Member feed
  ['Feed reading progress', 'फ़ीड पढ़ने की प्रगति'], ['More actions', 'और कार्रवाइयां'], ['Scroll to top', 'ऊपर जाएं'],
  ['My Help Posts', 'मेरी सहायता पोस्ट'], ['Photo source', 'तस्वीर स्रोत'], ['Close Help Request', 'सहायता अनुरोध बंद करें'],
  ['People in your network', 'आपके नेटवर्क के लोग'], ['Verified members', 'सत्यापित सदस्य'],
  ['Privacy-first help', 'गोपनीयता-आधारित सहायता'],
  ['Private conversations start only when a member selects “I Can Help” on an active post.', 'निजी बातचीत तभी शुरू होती है जब कोई सदस्य सक्रिय पोस्ट पर “मैं सहायता कर सकता/सकती हूं” चुनता है।'],
  ['Private chat starts directly with “I Can Help”, or after the post owner accepts a Volunteer request.', 'निजी चैट “मैं सहायता कर सकता/सकती हूं” से सीधे, या पोस्ट करने वाले द्वारा स्वयंसेवा अनुरोध स्वीकार करने के बाद शुरू होती है।'],
  ['Featured reading', 'विशेष लेख'], ['Ideas for an equal society', 'समान समाज के विचार'],
  ['Inspired by Dr. B. R. Ambedkar', 'डॉ. बी. आर. आंबेडकर से प्रेरित'], ['Top', 'ऊपर'],
  ['Member workspace', 'सदस्य कार्यक्षेत्र'], ['Loading your help requests…', 'आपके सहायता अनुरोध लोड हो रहे हैं…'],
  ['No help posts.', 'कोई सहायता पोस्ट नहीं है।'], ['Closed · History remains in Help Messenger.', 'बंद · इतिहास सहायता संदेश में उपलब्ध रहेगा।'],
  ['Close this help request?', 'क्या यह सहायता अनुरोध बंद करना है?'],
  ['Closing this post will remove it from the active feed, stop new help offers, close all related active conversations and disable reconnect requests.', 'इस पोस्ट को बंद करने पर यह सक्रिय फ़ीड से हटेगी, नए सहायता प्रस्ताव रुकेंगे, संबंधित सक्रिय बातचीत बंद होगी और दोबारा जुड़ने के अनुरोध अक्षम हो जाएंगे।'],
  ['The post and chat history will remain available for reference.', 'पोस्ट और चैट इतिहास संदर्भ के लिए उपलब्ध रहेंगे।'],
  ['English (India)', 'अंग्रेज़ी (भारत)'], ['हिन्दी (भारत)', 'हिन्दी (भारत)'], ['JPG / PNG · max 5 MB', 'JPG / PNG · अधिकतम 5 MB'],

  // Meetings
  ['Microphone muted', 'माइक्रोफ़ोन बंद'], ['Leave meeting', 'बैठक छोड़ें'], ['End meeting for everyone', 'सभी के लिए बैठक समाप्त करें'],
  ['Live meeting', 'लाइव बैठक'], ['Admin approved', 'प्रशासक द्वारा स्वीकृत'],
  ['Waiting for eligible members to join', 'योग्य सदस्यों के जुड़ने की प्रतीक्षा है'],
  ['Preparing your camera and secure connection...', 'आपका कैमरा और सुरक्षित कनेक्शन तैयार हो रहा है...'],
  ['Room details', 'बैठक कक्ष विवरण'], ['Audience', 'प्रतिभागी समूह'], ['Approved by', 'स्वीकृतकर्ता'], ['Agenda', 'कार्यसूची'],
  ['Only approved, eligible members can enter this room.', 'केवल स्वीकृत और योग्य सदस्य इस कक्ष में प्रवेश कर सकते हैं।'],
  ['Leave', 'छोड़ें'], ['End for all', 'सभी के लिए समाप्त करें'],
  ['What would you like to discuss?', 'आप किस विषय पर चर्चा करना चाहते हैं?'],
  ['Add context so the admin and members know what the meeting is about.', 'विवरण जोड़ें ताकि प्रशासक और सदस्यों को बैठक का विषय पता हो।'],
  ['Community conversations', 'सामुदायिक बातचीत'], ['Meetings', 'बैठकें'],
  ['Request once. An admin reviews it, then the room opens for the selected network.', 'एक बार अनुरोध करें। प्रशासक समीक्षा के बाद चुने हुए नेटवर्क के लिए कक्ष खोलता है।'],
  ['Request a meeting', 'बैठक का अनुरोध करें'], ['Admin approval is required before anyone can join.', 'किसी के जुड़ने से पहले प्रशासक की स्वीकृति आवश्यक है।'],
  ['Moderated', 'नियंत्रित'], ['Meeting title', 'बैठक का शीर्षक'], ['Who can join?', 'कौन जुड़ सकता है?'],
  ['Short agenda', 'संक्षिप्त कार्यसूची'], ['You will see the approval status here.', 'स्वीकृति की स्थिति यहां दिखाई देगी।'],
  ['Live now', 'अभी लाइव'], ['No live meetings right now', 'अभी कोई लाइव बैठक नहीं है'],
  ['Approved rooms will appear here automatically.', 'स्वीकृत कक्ष यहां स्वतः दिखाई देंगे।'], ['Your requests', 'आपके अनुरोध'],
  ['Enter room', 'कक्ष में जाएं'], ['How approval works', 'स्वीकृति कैसे काम करती है'], ['Send request', 'अनुरोध भेजें'],
  ['Add a title and audience.', 'शीर्षक और प्रतिभागी समूह जोड़ें।'], ['Admin reviews', 'प्रशासक समीक्षा करता है'],
  ['Safety and purpose are checked.', 'सुरक्षा और उद्देश्य की जांच होती है।'], ['Room goes live', 'कक्ष लाइव होता है'],
  ['Eligible members can join.', 'योग्य सदस्य जुड़ सकते हैं।'], ['Audience groups', 'प्रतिभागी समूह'],

  // Administration
  ['Administration sections', 'प्रशासन अनुभाग'], ['Close send invite', 'आमंत्रण भेजना बंद करें'], ['Send invite by', 'आमंत्रण भेजने का माध्यम'],
  ['Content type', 'सामग्री प्रकार'], ['Restore', 'बहाल करें'], ['Block from website', 'वेबसाइट पर अवरुद्ध करें'],
  ['Remove from website', 'वेबसाइट से हटाएं'], ['Field name', 'क्षेत्र का नाम'], ['Short description', 'संक्षिप्त विवरण'],
  ['Display order', 'प्रदर्शन क्रम'], ['Disable field', 'क्षेत्र निष्क्रिय करें'], ['Restore field', 'क्षेत्र बहाल करें'],
  ['Delete achiever', 'उपलब्धि प्रोफ़ाइल हटाएं'], ['Block from library', 'पुस्तकालय में अवरुद्ध करें'],
  ['Remove from library', 'पुस्तकालय से हटाएं'], ['Mark completed', 'पूर्ण चिह्नित करें'], ['Delete event', 'कार्यक्रम हटाएं'],
  ['Go live', 'लाइव करें'], ['Pause broadcast', 'प्रसारण रोकें'], ['End broadcast', 'प्रसारण समाप्त करें'],
  ['Delete programme', 'कार्यक्रम हटाएं'], ['Delete photo', 'तस्वीर हटाएं'], ['Workspace', 'कार्यक्षेत्र'],
  ['Health and priorities', 'स्थिति और प्राथमिकताएं'], ['Codes and requests', 'कोड और अनुरोध'],
  ['Leaders, books and media', 'नेता, पुस्तकें और मीडिया'], ['Members and meetings', 'सदस्य और बैठकें'],
  ['Posts and safety', 'पोस्ट और सुरक्षा'], ['Control centre', 'नियंत्रण केंद्र'], ['Administration overview', 'प्रशासन अवलोकन'],
  ['Outstanding work and website health, without unnecessary clutter.', 'लंबित कार्य और वेबसाइट की स्थिति—बिना अनावश्यक अव्यवस्था के।'],
  ['registered members', 'पंजीकृत सदस्य'], ['Invite requests', 'आमंत्रण अनुरोध'], ['Awaiting a decision', 'निर्णय की प्रतीक्षा'],
  ['Review →', 'समीक्षा करें →'], ['Meeting requests', 'बैठक अनुरोध'], ['Awaiting approval', 'स्वीकृति की प्रतीक्षा'],
  ['Managed resources', 'प्रबंधित संसाधन'], ['Leaders and books', 'नेता और पुस्तकें'], ['Manage →', 'प्रबंधित करें →'],
  ['Member access', 'सदस्य प्रवेश'], ['Invite code', 'आमंत्रण कोड'],
  ['Generate a single-use code and share it with a verified applicant.', 'एक बार उपयोग होने वाला कोड बनाकर सत्यापित आवेदक से साझा करें।'],
  ['Latest available invite', 'नवीनतम उपलब्ध आमंत्रण'], ['No unused invite code yet', 'अभी कोई अप्रयुक्त आमंत्रण कोड नहीं है'],
  ['Send invite', 'आमंत्रण भेजें'], ['Ready-to-send message', 'भेजने के लिए तैयार संदेश'],
  ['Registration link, invite code and both verification OTPs are included.', 'पंजीकरण लिंक, आमंत्रण कोड और दोनों सत्यापन OTP शामिल हैं।'],
  ['Registered members', 'पंजीकृत सदस्य'], ['Member invite-code requests', 'सदस्य आमंत्रण-कोड अनुरोध'],
  ['Members can request a code for a person they want to invite. Approve or reject each request.', 'सदस्य किसी व्यक्ति को आमंत्रित करने के लिए कोड मांग सकते हैं। प्रत्येक अनुरोध स्वीकार या अस्वीकार करें।'],
  ['No registered-member request is pending.', 'पंजीकृत सदस्य का कोई अनुरोध लंबित नहीं है।'],
  ['Approve & generate', 'स्वीकृत करें और कोड बनाएं'], ['Single-use member access', 'एक बार उपयोग वाला सदस्य प्रवेश'],
  ['Message preview', 'संदेश पूर्वावलोकन'], ['Continue to', 'आगे जाएं'],
  ["Your device's app will open with the recipient and message filled in.", 'आपके डिवाइस का ऐप प्राप्तकर्ता और संदेश के साथ खुलेगा।'],
  ['Applicant access', 'आवेदक प्रवेश'], ['Approve verified applicants to issue a secure single-use code.', 'सुरक्षित एकल-उपयोग कोड जारी करने के लिए सत्यापित आवेदक स्वीकृत करें।'],
  ['Code generated for', 'इसके लिए बनाया गया कोड'], ['No invite-code request is pending.', 'कोई आमंत्रण-कोड अनुरोध लंबित नहीं है।'],
  ['Total Users', 'कुल उपयोगकर्ता'], ['Active Posts', 'सक्रिय पोस्ट'], ['Public publishing', 'सार्वजनिक प्रकाशन'],
  ['Content Studio', 'सामग्री केंद्र'], ['One workspace for leaders, books, events, gallery and live media.', 'नेताओं, पुस्तकों, कार्यक्रमों, गैलरी और लाइव मीडिया के लिए एक कार्यक्षेत्र।'],
  ['Achievers', 'उपलब्धि प्राप्तकर्ता'], ['Library', 'पुस्तकालय'], ['Events', 'कार्यक्रम'], ['Live media', 'लाइव मीडिया'], ['Gallery', 'गैलरी'],
  ['Add a leader', 'नेता जोड़ें'], ['The profile becomes visible immediately and can be blocked or restored later.', 'प्रोफ़ाइल तुरंत दिखाई देगी और बाद में अवरुद्ध या बहाल की जा सकती है।'],
  ['Full name', 'पूरा नाम'], ['Era', 'काल'], ['Department / area', 'विभाग / क्षेत्र'], ['Contribution', 'योगदान'],
  ['Profile overview', 'प्रोफ़ाइल परिचय'], ['Photo URL', 'तस्वीर URL'], ['Community help fields', 'सामुदायिक सहायता क्षेत्र'],
  ['These categories power member profiles and the achievers directory.', 'ये श्रेणियां सदस्य प्रोफ़ाइल और उपलब्धि निर्देशिका में उपयोग होती हैं।'],
  ['Add field', 'क्षेत्र जोड़ें'], ['Disable', 'निष्क्रिय करें'], ['Add a top achiever', 'शीर्ष उपलब्धि प्राप्तकर्ता जोड़ें'],
  ['Publish verified accomplishments under a clear professional category.', 'सत्यापित उपलब्धियों को स्पष्ट पेशेवर श्रेणी में प्रकाशित करें।'],
  ['Select category', 'श्रेणी चुनें'], ['Professional title', 'पेशेवर पद'], ['Key achievement', 'मुख्य उपलब्धि'],
  ['Profile summary', 'प्रोफ़ाइल सारांश'], ['Reference URL', 'संदर्भ URL'], ['Top achievers directory', 'शीर्ष उपलब्धि निर्देशिका'],
  ['No achiever profile has been published.', 'कोई उपलब्धि प्रोफ़ाइल प्रकाशित नहीं हुई है।'],
  ['Add a library book', 'पुस्तकालय में पुस्तक जोड़ें'], ['Add a free PDF or a print-store edition.', 'निःशुल्क PDF या मुद्रित संस्करण जोड़ें।'],
  ['Book title', 'पुस्तक शीर्षक'], ['Author', 'लेखक'], ['Collection', 'संग्रह'], ['Print edition', 'मुद्रित संस्करण'],
  ['Cover image URL', 'मुखपृष्ठ तस्वीर URL'], ['Library catalogue', 'पुस्तकालय सूची'], ['books', 'पुस्तकें'],
  ['Publish an event', 'कार्यक्रम प्रकाशित करें'], ['It will appear immediately on Events & Notices.', 'यह कार्यक्रम और सूचनाएं पृष्ठ पर तुरंत दिखाई देगा।'],
  ['Event title', 'कार्यक्रम शीर्षक'], ['Venue', 'स्थान'], ['Date and time', 'तिथि और समय'], ['Registration URL', 'पंजीकरण URL'],
  ['Published events', 'प्रकाशित कार्यक्रम'], ['total', 'कुल'], ['No event has been published.', 'कोई कार्यक्रम प्रकाशित नहीं हुआ है।'],
  ['Create a programme', 'कार्यक्रम बनाएं'], ['Add it first, then use Go live when ready.', 'पहले इसे जोड़ें, तैयार होने पर लाइव करें।'],
  ['Programme title', 'कार्यक्रम शीर्षक'], ['Host name', 'मेज़बान का नाम'], ['Media type', 'मीडिया प्रकार'],
  ['Direct video', 'सीधा वीडियो'], ['Audio podcast', 'ऑडियो पॉडकास्ट'], ['Media URL', 'मीडिया URL'],
  ['Scheduled time', 'निर्धारित समय'], ['Broadcast queue', 'प्रसारण कतार'], ['No programme has been created.', 'कोई कार्यक्रम नहीं बनाया गया है।'],
  ['Upload an event photo', 'कार्यक्रम तस्वीर अपलोड करें'], ['JPG or PNG, up to 8 MB.', 'JPG या PNG, अधिकतम 8 MB।'],
  ['Photo', 'तस्वीर'], ['Photo title', 'तस्वीर शीर्षक'], ['Caption', 'विवरण'], ['Related event', 'संबंधित कार्यक्रम'],
  ['General community photo', 'सामान्य सामुदायिक तस्वीर'], ['Published gallery', 'प्रकाशित गैलरी'],
  ['No gallery photo has been published.', 'कोई गैलरी तस्वीर प्रकाशित नहीं हुई है।'],
  ['Meeting Approvals', 'बैठक स्वीकृतियां'], ['Review requests before a room becomes available to the network.', 'कक्ष को नेटवर्क के लिए खोलने से पहले अनुरोधों की समीक्षा करें।'],
  ['No meeting requests need review.', 'किसी बैठक अनुरोध की समीक्षा लंबित नहीं है।'], ['Approve & Go Live', 'स्वीकृत कर लाइव करें'],
  ['User Management', 'उपयोगकर्ता प्रबंधन'], ['Professional Group', 'पेशेवर समूह'], ['ID Proof', 'पहचान प्रमाण'],
  ['Content Moderation', 'सामग्री नियंत्रण'], ['Review active community posts and remove content that violates community standards.', 'सक्रिय सामुदायिक पोस्ट की समीक्षा करें और नियमों का उल्लंघन करने वाली सामग्री हटाएं।'],
  ['No active posts require attention.', 'किसी सक्रिय पोस्ट पर ध्यान देने की आवश्यकता नहीं है।'], ['Delete Post', 'पोस्ट हटाएं'],
  ['Invite Codes', 'आमंत्रण कोड'], ['Audit available and previously used single-use access codes.', 'उपलब्ध और पहले उपयोग किए गए एकल-उपयोग प्रवेश कोड की जांच करें।'],
  ['Filter leaders', 'नेता फ़िल्टर करें'], ['Search people or work', 'व्यक्ति या कार्य खोजें'], ['Search leaders', 'नेता खोजें'],
  ['Previous leaders', 'पिछले नेता'], ['Next leaders', 'अगले नेता'], ['Previous blogs', 'पिछले लेख'], ['Next blogs', 'अगले लेख'],
  ['Scroll leaders left', 'नेताओं को बाईं ओर स्क्रॉल करें'], ['Scroll leaders right', 'नेताओं को दाईं ओर स्क्रॉल करें'],
  ['Achiever categories', 'उपलब्धि श्रेणियां'], ['Live community video', 'लाइव सामुदायिक वीडियो'], ['PDF', 'PDF'],
  ['View all top achievers', 'सभी शीर्ष उपलब्धि प्राप्तकर्ता देखें'],
  ['pending', 'लंबित'], ['active', 'सक्रिय'], ['profiles', 'प्रोफ़ाइल'], ['fields', 'क्षेत्र'], ['programmes', 'कार्यक्रम'],
  ['photos', 'तस्वीरें'], ['members', 'सदस्य'], ['helpers', 'सहायक'], ['active chats', 'सक्रिय चैट'],
  ['participants', 'प्रतिभागी'], ['rooms', 'कक्ष'], ['achievers', 'उपलब्धि प्राप्तकर्ता'], ['readings', 'लेख'], ['scheduled', 'निर्धारित'],
  ['Close invite request', 'आमंत्रण अनुरोध बंद करें'], ['Your invite request for', 'आपका आमंत्रण अनुरोध'],
  ['Send this complete registration message to', 'यह पूरा पंजीकरण संदेश इन्हें भेजें'],
  ['UPSC ranker, senior advocate, doctor...', 'UPSC रैंकधारी, वरिष्ठ अधिवक्ता, चिकित्सक...'],
  ['Your device’s app will open with the recipient and message filled in.', 'आपके डिवाइस का ऐप प्राप्तकर्ता और संदेश के साथ खुलेगा।'],
  ['All verified members', 'सभी सत्यापित सदस्य'], ['Healthcare group', 'स्वास्थ्य सेवा समूह'],
  ['Engineering group', 'इंजीनियरिंग समूह'], ['Teachers and educators', 'शिक्षक और शिक्षाविद'], ['Community service group', 'सामुदायिक सेवा समूह'],
  ['Request sent. The meeting will go live as soon as an admin approves it.', 'अनुरोध भेज दिया गया है। प्रशासक की स्वीकृति मिलते ही बैठक लाइव हो जाएगी।'],
  ['Meeting request could not be sent', 'बैठक अनुरोध नहीं भेजा जा सका'], ['Unable to join this meeting', 'इस बैठक में शामिल नहीं हो सके'],
  ['Meetings could not be loaded', 'बैठकें लोड नहीं हो सकीं'], ['Meeting could not be ended', 'बैठक समाप्त नहीं की जा सकी'],
  ['You cannot join this meeting', 'आप इस बैठक में शामिल नहीं हो सकते'],
  ['Camera and microphone require HTTPS or localhost.', 'कैमरा और माइक्रोफ़ोन के लिए HTTPS या localhost आवश्यक है।'],
  ['Camera and microphone are unavailable. You can still join in listen-only mode.', 'कैमरा और माइक्रोफ़ोन उपलब्ध नहीं हैं। आप केवल सुनने के मोड में शामिल हो सकते हैं।'],
  ['The host ended this meeting.', 'मेज़बान ने यह बैठक समाप्त कर दी है।'],
  ['A participant connection was interrupted. Reconnecting may help.', 'एक प्रतिभागी का कनेक्शन टूट गया। दोबारा जुड़ने से समस्या हल हो सकती है।'],
  ['This meeting has ended.', 'यह बैठक समाप्त हो चुकी है।'],
  ['Active help chats could not be loaded.', 'सक्रिय सहायता चैट लोड नहीं हो सकीं।'],
  ['Chat history could not be loaded.', 'चैट इतिहास लोड नहीं हो सका।'], ['Conversation could not be loaded.', 'बातचीत लोड नहीं हो सकी।'],
  ['Message could not be sent.', 'संदेश नहीं भेजा जा सका।'], ['Conversation could not be ended.', 'बातचीत समाप्त नहीं की जा सकी।'],
  ['Reconnect request could not be sent.', 'दोबारा जुड़ने का अनुरोध नहीं भेजा जा सका।'],
  ['Reconnect request could not be updated.', 'दोबारा जुड़ने का अनुरोध अपडेट नहीं हो सका।'],
  ['Open the matching post in the feed to offer help.', 'सहायता देने के लिए फ़ीड में संबंधित पोस्ट खोलें।'],
  ['Member could not be blocked.', 'सदस्य को अवरुद्ध नहीं किया जा सका।'],
  ['Briefly describe the safety concern:', 'सुरक्षा संबंधी चिंता का संक्षिप्त विवरण दें:'], ['Inappropriate behaviour', 'अनुचित व्यवहार'],
  ['Report submitted for admin review.', 'रिपोर्ट प्रशासक की समीक्षा के लिए भेजी गई।'], ['Report could not be submitted.', 'रिपोर्ट जमा नहीं हो सकी।'],
  ['Complete all registration steps before submitting your account.', 'खाता जमा करने से पहले पंजीकरण के सभी चरण पूरे करें।'],
  ['Verify both email and mobile number before creating your account.', 'खाता बनाने से पहले ईमेल और मोबाइल नंबर दोनों सत्यापित करें।'],
  ['Registration complete. Your verified account is ready to use.', 'पंजीकरण पूरा हुआ। आपका सत्यापित खाता उपयोग के लिए तैयार है।'],
  ['Registration failed', 'पंजीकरण विफल रहा'], ['Enter your name and select at least one field where you can help.', 'अपना नाम दर्ज करें और सहायता का कम से कम एक क्षेत्र चुनें।'],
  ['Verify both email and mobile number before continuing.', 'आगे बढ़ने से पहले ईमेल और मोबाइल नंबर दोनों सत्यापित करें।'],
  ['Could not generate OTP', 'OTP नहीं बनाया जा सका'], ['OTP verification failed', 'OTP सत्यापन विफल रहा'],
  ['Verify both email and mobile number before requesting an invite code.', 'आमंत्रण कोड मांगने से पहले ईमेल और मोबाइल नंबर दोनों सत्यापित करें।'],
  ['Invite request sent. It will appear here automatically after admin approval.', 'आमंत्रण अनुरोध भेज दिया गया है। प्रशासक की स्वीकृति के बाद यह यहां स्वतः दिखाई देगा।'],
  ['Invite request could not be sent', 'आमंत्रण अनुरोध नहीं भेजा जा सका'],
  ['Your invite request was approved. The code has been added automatically.', 'आपका आमंत्रण अनुरोध स्वीकृत हो गया। कोड स्वतः जोड़ दिया गया है।'],
  ['Identity verified. Create your new password.', 'पहचान सत्यापित हुई। अपना नया पासवर्ड बनाएं।'], ['Password reset failed', 'पासवर्ड रीसेट विफल रहा'],
  ['Post text cannot exceed 3000 characters.', 'पोस्ट का पाठ 3000 अक्षरों से अधिक नहीं हो सकता।'],
  ['Image upload failed. Please try again.', 'तस्वीर अपलोड विफल रही। फिर प्रयास करें।'], ['Only JPG and PNG images are allowed.', 'केवल JPG और PNG तस्वीरें मान्य हैं।'],
  ['Image size must be 5 MB or less.', 'तस्वीर का आकार 5 MB या कम होना चाहिए।'], ['Comments could not be loaded.', 'टिप्पणियां लोड नहीं हो सकीं।'],
  ['Comment could not be sent.', 'टिप्पणी नहीं भेजी जा सकी।'], ['Support could not be updated.', 'समर्थन अपडेट नहीं हो सका।'],
  ['Help conversation started. Open Help Messages to continue.', 'सहायता बातचीत शुरू हुई। आगे बढ़ने के लिए सहायता संदेश खोलें।'],
  ['Help offer could not be started.', 'सहायता प्रस्ताव शुरू नहीं हो सका।'], ['Your help posts could not be loaded.', 'आपकी सहायता पोस्ट लोड नहीं हो सकीं।'],
  ['I Can Help', 'मैं सहायता कर सकता/सकती हूं'], ['Starting…', 'शुरू हो रहा है…'],
  ['Volunteer', 'स्वयंसेवा'], ['Volunteer request', 'स्वयंसेवा अनुरोध'], ['Volunteer requests', 'स्वयंसेवा अनुरोध'], ['Open chat', 'चैट खोलें'],
  ['Volunteer request accepted', 'स्वयंसेवा अनुरोध स्वीकृत'], ['Volunteer request declined', 'स्वयंसेवा अनुरोध अस्वीकृत'],
  ['Help requested from everyone', 'सभी से सहायता मांगी गई'],
  ['Volunteer request sent. The post owner can open a private chat from Help Messenger.', 'स्वयंसेवा अनुरोध भेज दिया गया है। पोस्ट करने वाला सहायता संदेश से निजी चैट खोल सकता है।'],
  ['Volunteer request could not be sent.', 'स्वयंसेवा अनुरोध नहीं भेजा जा सका।'], ['Volunteer request could not be updated.', 'स्वयंसेवा अनुरोध अपडेट नहीं हो सका।'],
  ['Request to all', 'सभी से सहायता मांगें'], ['Sent to all community members', 'सभी समुदाय सदस्यों को भेजा गया'],
  ['Request to all could not be sent.', 'सभी से सहायता का अनुरोध नहीं भेजा जा सका।'], ['volunteers pending', 'स्वयंसेवक लंबित'],
  ['Sending…', 'भेजा जा रहा है…'],
  ['Help request could not be closed.', 'सहायता अनुरोध बंद नहीं किया जा सका।'], ['Post could not be created.', 'पोस्ट नहीं बनाई जा सकी।'],
  ['Network connection unavailable. Please check your internet and try again.', 'नेटवर्क कनेक्शन उपलब्ध नहीं है। इंटरनेट जांचकर फिर प्रयास करें।'],
  ['Network connection unavailable. Check your internet and try again.', 'नेटवर्क कनेक्शन उपलब्ध नहीं है। इंटरनेट जांचकर फिर प्रयास करें।'],
  ['Copy failed. Select the code and copy it manually.', 'कॉपी नहीं हो सका। कोड चुनकर स्वयं कॉपी करें।'],
  ['Copy failed. Select the invite message and copy it manually.', 'कॉपी नहीं हो सका। आमंत्रण संदेश चुनकर स्वयं कॉपी करें।'],
  ['Copy failed. Select the message and copy it manually.', 'कॉपी नहीं हो सका। संदेश चुनकर स्वयं कॉपी करें।']
]);

export function translateUiText(value: string): string {
  const exact = UI_HI[value];
  if (exact) return exact;
  const patterns: Array<[RegExp, string]> = [
    [/^(\d+) selected · maximum 8$/, '$1 चयनित · अधिकतम 8'],
    [/^Requested (.+)$/, 'अनुरोध: $1'],
    [/^Hosted by (.+)$/, 'मेज़बान: $1'],
    [/^Approved by (.+)$/, 'स्वीकृतकर्ता: $1'],
    [/^Regarding: (.+)$/, 'संबंधित: $1'],
    [/^Session (\d+) · Private help conversation$/, 'सत्र $1 · निजी सहायता बातचीत'],
    [/^(\d+) participants$/, '$1 प्रतिभागी'],
    [/^(\d+) members$/, '$1 सदस्य'],
    [/^(\d+) helpers$/, '$1 सहायक'],
    [/^(\d+) active chats$/, '$1 सक्रिय चैट'],
    [/^(\d+) profiles$/, '$1 प्रोफ़ाइल'],
    [/^(\d+) achievers$/, '$1 उपलब्धि प्राप्तकर्ता'],
    [/^(\d+) readings$/, '$1 लेख'],
    [/^(\d+) photos$/, '$1 तस्वीरें'],
    [/^(\d+) programmes$/, '$1 कार्यक्रम'],
    [/^(\d+) scheduled$/, '$1 निर्धारित'],
    [/^Ended by (.+)$/, '$1 द्वारा समाप्त'],
    [/^Posting as (.+)$/, '$1 के रूप में पोस्ट'],
    [/^For: (.+)$/, 'के लिए: $1']
    ,[/^Block (.+)\? Messaging and reconnect requests will be disabled\.$/, '$1 को अवरुद्ध करें? संदेश और दोबारा जुड़ने के अनुरोध बंद हो जाएंगे।']
    ,[/^(Email|Mobile) testing OTP: (.+)$/, '$1 परीक्षण OTP: $2']
    ,[/^(Email|Mobile number) verified successfully\.$/, '$1 सफलतापूर्वक सत्यापित हुआ।']
    ,[/^Hosted by (.+) · (\d+) joined$/, 'मेज़बान: $1 · $2 जुड़े']
    ,[/^(.+) volunteered to help with “(.+)”\. Open Help Messenger to review\.$/, '$1 ने “$2” में सहायता के लिए स्वयंसेवा की है। समीक्षा के लिए सहायता संदेश खोलें।']
    ,[/^(.+) opened a help chat for “(.+)”\.$/, '$1 ने “$2” के लिए सहायता चैट खोल दी है।']
    ,[/^(.+) declined your volunteer request for “(.+)”\.$/, '$1 ने “$2” के लिए आपका स्वयंसेवा अनुरोध अस्वीकार कर दिया।']
    ,[/^(.+) requested community help: (.+)$/, '$1 ने समुदाय से सहायता मांगी: $2']
  ];
  for (const [pattern, replacement] of patterns) if (pattern.test(value)) return value.replace(pattern, replacement);
  return value;
}
