package com.sc.community.service;

import com.sc.community.dto.HelpChatDtos.*;
import com.sc.community.entity.*;
import com.sc.community.repository.*;
import jakarta.transaction.Transactional;
import java.time.*;
import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.*;
import org.springframework.web.server.ResponseStatusException;

@Service
public class HelpChatService {
 private final PostRepository posts; private final HelpConversationRepository conversations; private final HelpMessageRepository messages;
 private final HelpReconnectRequestRepository reconnects; private final UserBlockRepository blocks; private final HelpNotificationRepository notifications;
 private final HelpAuditEventRepository audits; private final UserRepository users; private final ReportRepository reports;
 private final CurrentUserService current; private final DirectoryService directory; private final SimpMessagingTemplate socket;
 public HelpChatService(PostRepository posts,HelpConversationRepository conversations,HelpMessageRepository messages,HelpReconnectRequestRepository reconnects,UserBlockRepository blocks,HelpNotificationRepository notifications,HelpAuditEventRepository audits,UserRepository users,ReportRepository reports,CurrentUserService current,DirectoryService directory,SimpMessagingTemplate socket){this.posts=posts;this.conversations=conversations;this.messages=messages;this.reconnects=reconnects;this.blocks=blocks;this.notifications=notifications;this.audits=audits;this.users=users;this.reports=reports;this.current=current;this.directory=directory;this.socket=socket;}

 @Transactional public void notifyNewPost(Post post){
  for(User user:users.findByStatus(UserStatus.VERIFIED)){ if(user.getId().equals(post.getUser().getId())||user.getRole()==UserRole.ROLE_ADMIN)continue; directory.populateHelpFields(user); if(relevant(user,post)) notify(user,HelpNotificationType.NEW_HELP_POST,post,null,"New "+post.getCategory().getName(),post.getUser().getFullName()+" requested help: "+title(post),"new-post:"+post.getId()+":"+user.getId()); }
 }
 @Transactional public ConversationResponse offer(Long postId){
  User helper=current.verifiedUser(); Post post=posts.findLockedById(postId).orElseThrow(()->notFound("Help post not found"));
  requireOpen(post); if(post.getUser().getId().equals(helper.getId()))throw bad("You cannot offer help on your own post"); requireActive(helper); requireActive(post.getUser()); requireNotBlocked(helper,post.getUser());
  HelpConversation existing=conversations.findByPostIdAndHelperId(postId,helper.getId()).orElse(null);
  if(existing!=null){ if(existing.getStatus()==HelpConversationStatus.ACTIVE)return response(existing,helper); throw bad("This help conversation already exists. Use Chat History to reconnect."); }
  HelpConversation c=new HelpConversation();c.setPost(post);c.setRequester(post.getUser());c.setHelper(helper);
  try{c=conversations.saveAndFlush(c);}catch(DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"A help conversation already exists");}
  audit("CONVERSATION_STARTED",helper,post,c); notify(post.getUser(),HelpNotificationType.HELP_OFFER_RECEIVED,post,c,"Help offer received",helper.getFullName()+" can help with “"+title(post)+"”.","offer:"+c.getId()); publish("CONVERSATION_STARTED",c); return response(c,helper);
 }
 @Transactional public VolunteerRequestResponse volunteer(Long postId){
  User helper=current.verifiedUser();Post post=posts.findLockedById(postId).orElseThrow(()->notFound("Help post not found"));requireOpen(post);if(post.getUser().getId().equals(helper.getId()))throw bad("You cannot volunteer on your own post");requireActive(helper);requireActive(post.getUser());requireNotBlocked(helper,post.getUser());
  HelpConversation existingConversation=conversations.findByPostIdAndHelperId(postId,helper.getId()).orElse(null);if(existingConversation!=null)throw new ResponseStatusException(HttpStatus.CONFLICT,existingConversation.getStatus()==HelpConversationStatus.ACTIVE?"Your help chat is already open":"Use Chat History to reconnect with this member");
  String key="volunteer:"+postId+":"+helper.getId();HelpNotification existing=notifications.findByDedupeKey(key).orElse(null);if(existing!=null){if(existing.isRead())throw new ResponseStatusException(HttpStatus.CONFLICT,"This volunteer request has already been reviewed");return volunteerResponse(existing,helper,"PENDING",null,null);}
  HelpNotification request=new HelpNotification();request.setRecipient(post.getUser());request.setType(HelpNotificationType.VOLUNTEER_REQUEST);request.setPost(post);request.setTitle("Volunteer request");request.setBody(helper.getFullName()+" volunteered to help with “"+title(post)+"”. Open Help Messenger to review.");request.setDedupeKey(key);request=notifications.save(request);audit("VOLUNTEER_REQUESTED",helper,post,null);publishUser("VOLUNTEER_REQUEST",post.getUser().getId(),postId);return volunteerResponse(request,helper,"PENDING",null,null);
 }
 @Transactional public List<VolunteerRequestResponse> incomingVolunteers(){User u=current.verifiedUser();return notifications.findByRecipientIdAndTypeAndReadFalseOrderByCreatedAtDesc(u.getId(),HelpNotificationType.VOLUNTEER_REQUEST).stream().map(n->volunteerResponse(n,volunteerUser(n),"PENDING",null,null)).toList();}
 @Transactional public VolunteerRequestResponse decideVolunteer(Long requestId,boolean accept){
  User owner=current.verifiedUser();HelpNotification snapshot=notifications.findById(requestId).orElseThrow(()->notFound("Volunteer request not found"));if(snapshot.getPost()==null)throw bad("Volunteer request is invalid");Post post=posts.findLockedById(snapshot.getPost().getId()).orElseThrow(()->notFound("Help post not found"));HelpNotification request=notifications.findLockedById(requestId).orElseThrow(()->notFound("Volunteer request not found"));if(request.getType()!=HelpNotificationType.VOLUNTEER_REQUEST||!request.getRecipient().getId().equals(owner.getId()))throw forbidden("This volunteer request is not for you");if(request.isRead())throw bad("Volunteer request has already been decided");requireOpen(post);User helper=volunteerUser(request);Instant respondedAt=Instant.now();request.setRead(true);
  if(!accept){audit("VOLUNTEER_DECLINED",owner,post,null);notify(helper,HelpNotificationType.VOLUNTEER_DECLINED,post,null,"Volunteer request declined",owner.getFullName()+" declined your volunteer request for “"+title(post)+"”.","volunteer-declined:"+request.getId());publishUser("VOLUNTEER_DECLINED",helper.getId(),post.getId());return volunteerResponse(request,helper,"DECLINED",null,respondedAt);}
  requireActive(helper);requireNotBlocked(owner,helper);HelpConversation conversation=conversations.findByPostIdAndHelperId(post.getId(),helper.getId()).orElse(null);if(conversation==null){conversation=new HelpConversation();conversation.setPost(post);conversation.setRequester(owner);conversation.setHelper(helper);conversation=conversations.saveAndFlush(conversation);}else if(conversation.getStatus()!=HelpConversationStatus.ACTIVE)throw bad("An ended conversation already exists. Use Chat History to reconnect.");audit("VOLUNTEER_ACCEPTED",owner,post,conversation);notify(helper,HelpNotificationType.VOLUNTEER_ACCEPTED,post,conversation,"Volunteer request accepted",owner.getFullName()+" opened a help chat for “"+title(post)+"”.","volunteer-accepted:"+request.getId());publish("VOLUNTEER_ACCEPTED",conversation);return volunteerResponse(request,helper,"ACCEPTED",conversation.getId(),respondedAt);
 }
 @Transactional public MyHelpPostResponse requestAll(Long postId){
  User owner=current.verifiedUser();Post post=posts.findLockedById(postId).orElseThrow(()->notFound("Help post not found"));if(!post.getUser().getId().equals(owner.getId()))throw forbidden("Only the post creator can request help from everyone");requireOpen(post);if(audits.findFirstByPostIdAndEventTypeOrderByCreatedAtDesc(postId,"HELP_REQUEST_EXPANDED").isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"This request has already been sent to everyone");if(conversations.countByPostId(postId)>0||notifications.countByPostIdAndTypeAndReadFalse(postId,HelpNotificationType.VOLUNTEER_REQUEST)>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Request to all is available only while no one has responded");for(User user:users.findByStatus(UserStatus.VERIFIED)){if(user.getId().equals(owner.getId())||user.getRole()==UserRole.ROLE_ADMIN)continue;notify(user,HelpNotificationType.HELP_REQUEST_EXPANDED,post,null,"Help requested from everyone",owner.getFullName()+" requested community help: "+title(post),"request-all:"+postId+":"+user.getId());publishUser("HELP_REQUEST_EXPANDED",user.getId(),postId);}audit("HELP_REQUEST_EXPANDED",owner,post,null);publishPost("HELP_REQUEST_EXPANDED",postId);return myPost(post,null);
 }
 @Transactional public List<ConversationResponse> list(String view){User u=current.verifiedUser();List<HelpConversation> rows="HISTORY".equalsIgnoreCase(view)?conversations.history(u.getId()):conversations.forUserByStatus(u.getId(),HelpConversationStatus.ACTIVE);return rows.stream().map(c->response(c,u)).toList();}
 @Transactional public List<HelpMessageResponse> messageHistory(Long id){User u=current.verifiedUser();HelpConversation c=requireParticipant(id,u,false);return messages.findByConversationIdOrderByCreatedAtAsc(c.getId()).stream().map(HelpMessageResponse::from).toList();}
 @Transactional public HelpMessageResponse send(Long id,String body){
  User sender=current.verifiedUser(); HelpConversation snapshot=conversations.findById(id).orElseThrow(()->notFound("Conversation not found")); Post post=posts.findLockedById(snapshot.getPost().getId()).orElseThrow(()->notFound("Help post not found")); HelpConversation c=requireParticipant(id,sender,true);
  requireOpen(post);if(c.getStatus()!=HelpConversationStatus.ACTIVE)throw forbidden("This conversation is no longer active");User recipient=other(c,sender);requireActive(recipient);requireNotBlocked(sender,recipient);
  HelpMessage m=new HelpMessage();m.setConversation(c);m.setSender(sender);m.setMessageBody(body.trim());m=messages.save(m);c.setLastMessageAt(m.getCreatedAt()==null?Instant.now():m.getCreatedAt());
  notify(recipient,HelpNotificationType.NEW_HELP_MESSAGE,post,c,"New help message",sender.getFullName()+" sent a message regarding “"+title(post)+"”.","message:"+(m.getId()==null?UUID.randomUUID():m.getId()));publish("NEW_HELP_MESSAGE",c);return HelpMessageResponse.from(m);
 }
 @Transactional public ConversationResponse end(Long id,String reason){
  User u=current.verifiedUser();HelpConversation snapshot=conversations.findById(id).orElseThrow(()->notFound("Conversation not found"));Post post=posts.findLockedById(snapshot.getPost().getId()).orElseThrow(()->notFound("Help post not found"));HelpConversation c=requireParticipant(id,u,true);requireOpen(post);if(c.getStatus()!=HelpConversationStatus.ACTIVE)throw bad("Conversation is not active");
  c.setStatus(HelpConversationStatus.ENDED_BY_USER);c.setEndedAt(Instant.now());c.setEndedBy(u);c.setEndReason(reason==null||reason.isBlank()?"Ended by participant":reason.trim());cancelPending(c);User recipient=other(c,u);audit("CONVERSATION_ENDED",u,post,c);notify(recipient,HelpNotificationType.CONVERSATION_ENDED,post,c,"Conversation ended",u.getFullName()+" ended your conversation regarding “"+title(post)+"”.","ended:"+c.getId()+":"+c.getSessionNumber());publish("CONVERSATION_ENDED",c);return response(c,u);
 }
 @Transactional public ReconnectResponse requestReconnect(Long id){
  User u=current.verifiedUser();HelpConversation snapshot=conversations.findById(id).orElseThrow(()->notFound("Conversation not found"));Post post=posts.findLockedById(snapshot.getPost().getId()).orElseThrow(()->notFound("Help post not found"));HelpConversation c=requireParticipant(id,u,true);requireOpen(post);if(c.getStatus()!=HelpConversationStatus.ENDED_BY_USER)throw bad("Only an ended conversation can be reconnected");User to=other(c,u);requireActive(to);requireNotBlocked(u,to);if(reconnects.findByConversationIdAndStatus(id,ReconnectRequestStatus.PENDING).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"A reconnect request is already pending");
  reconnects.findFirstByConversationIdOrderByCreatedAtDesc(id).filter(r->r.getStatus()==ReconnectRequestStatus.DECLINED&&r.getRespondedAt()!=null&&r.getRespondedAt().isAfter(Instant.now().minus(Duration.ofHours(24)))).ifPresent(r->{throw new ResponseStatusException(HttpStatus.TOO_MANY_REQUESTS,"Please wait 24 hours before requesting again");});
  HelpReconnectRequest r=new HelpReconnectRequest();r.setConversation(c);r.setRequestedBy(u);r.setRequestedTo(to);try{r=reconnects.saveAndFlush(r);}catch(DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"A reconnect request is already pending");}audit("RECONNECT_REQUESTED",u,post,c);notify(to,HelpNotificationType.RECONNECT_REQUEST,post,c,"Reconnect request",u.getFullName()+" wants to reconnect regarding “"+title(post)+"”.","reconnect:"+r.getId());publish("RECONNECT_REQUEST",c);return ReconnectResponse.from(r);
 }
 @Transactional public ReconnectResponse decide(Long requestId,boolean accept){
  User u=current.verifiedUser();HelpReconnectRequest snapshot=reconnects.findById(requestId).orElseThrow(()->notFound("Reconnect request not found"));Post post=posts.findLockedById(snapshot.getConversation().getPost().getId()).orElseThrow(()->notFound("Help post not found"));HelpReconnectRequest r=reconnects.findLockedById(requestId).orElseThrow(()->notFound("Reconnect request not found"));if(!r.getRequestedTo().getId().equals(u.getId()))throw forbidden("This reconnect request is not for you");if(r.getStatus()!=ReconnectRequestStatus.PENDING)throw bad("Reconnect request has already been decided");HelpConversation c=conversations.findLockedById(r.getConversation().getId()).orElseThrow(()->notFound("Conversation not found"));requireOpen(post);requireNotBlocked(r.getRequestedBy(),u);if(c.getStatus()!=HelpConversationStatus.ENDED_BY_USER)throw bad("Conversation cannot be reconnected");r.setRespondedAt(Instant.now());
  if(accept){r.setStatus(ReconnectRequestStatus.ACCEPTED);c.setStatus(HelpConversationStatus.ACTIVE);c.setSessionNumber(c.getSessionNumber()+1);c.setActivatedAt(Instant.now());c.setEndedAt(null);c.setEndedBy(null);c.setEndReason(null);audit("RECONNECT_ACCEPTED",u,post,c);notify(r.getRequestedBy(),HelpNotificationType.RECONNECT_ACCEPTED,post,c,"Reconnect accepted",u.getFullName()+" accepted your reconnect request.","reconnect-accepted:"+r.getId());publish("RECONNECT_ACCEPTED",c);}else{r.setStatus(ReconnectRequestStatus.DECLINED);audit("RECONNECT_DECLINED",u,post,c);notify(r.getRequestedBy(),HelpNotificationType.RECONNECT_DECLINED,post,c,"Reconnect declined",u.getFullName()+" declined your reconnect request.","reconnect-declined:"+r.getId());publish("RECONNECT_DECLINED",c);}return ReconnectResponse.from(r);
 }
 @Transactional public List<ReconnectResponse> incoming(){User u=current.verifiedUser();return reconnects.findByRequestedToIdAndStatusOrderByCreatedAtDesc(u.getId(),ReconnectRequestStatus.PENDING).stream().map(ReconnectResponse::from).toList();}
 @Transactional public MyHelpPostResponse closePost(Long postId){
  User u=current.verifiedUser();Post post=posts.findLockedById(postId).orElseThrow(()->notFound("Help post not found"));if(!post.getUser().getId().equals(u.getId()))throw forbidden("Only the post creator can close this help request");requireOpen(post);Instant now=Instant.now();post.setStatus(PostStatus.CLOSED);post.setClosedAt(now);post.setClosedBy(u);List<HelpConversation> active=conversations.lockByPostAndStatus(postId,HelpConversationStatus.ACTIVE);for(HelpConversation c:active){c.setStatus(HelpConversationStatus.ENDED_POST_CLOSED);c.setEndedAt(now);c.setEndedBy(u);c.setEndReason("Help request closed");User helper=c.getHelper();notify(helper,HelpNotificationType.POST_CLOSED,post,c,"Help request closed",u.getFullName()+" closed “"+title(post)+"”. The related conversation has ended.","post-closed:"+postId+":"+helper.getId());publish("POST_CLOSED",c);}for(HelpReconnectRequest r:reconnects.findByConversationPostIdAndStatus(postId,ReconnectRequestStatus.PENDING)){r.setStatus(ReconnectRequestStatus.CANCELLED);r.setRespondedAt(now);}for(HelpNotification request:notifications.findByPostIdAndTypeAndReadFalse(postId,HelpNotificationType.VOLUNTEER_REQUEST)){request.setRead(true);User helper=volunteerUser(request);notify(helper,HelpNotificationType.POST_CLOSED,post,null,"Help request closed",u.getFullName()+" closed “"+title(post)+"”. Your volunteer request was cancelled.","volunteer-cancelled:"+request.getId());publishUser("POST_CLOSED",helper.getId(),postId);}audit("POST_CLOSED",u,post,null);publishPost("POST_CLOSED",postId);return myPost(post,now);
 }
 @Transactional public List<MyHelpPostResponse> myPosts(PostStatus status){if(status!=PostStatus.ACTIVE&&status!=PostStatus.CLOSED)throw bad("Use ACTIVE or CLOSED status");User u=current.verifiedUser();return posts.findByUserIdAndStatusOrderByCreatedAtDesc(u.getId(),status).stream().map(p->myPost(p,null)).toList();}
 @Transactional public void block(Long id){User u=current.verifiedUser();HelpConversation c=requireParticipant(id,u,true);User other=other(c,u);if(blocks.findByBlockerIdAndBlockedId(u.getId(),other.getId()).isEmpty()){UserBlock b=new UserBlock();b.setBlocker(u);b.setBlocked(other);blocks.save(b);}for(HelpConversation row:conversations.between(u.getId(),other.getId())){cancelPending(row);if(row.getStatus()==HelpConversationStatus.ACTIVE){row.setStatus(HelpConversationStatus.BLOCKED);row.setEndedAt(Instant.now());row.setEndedBy(u);row.setEndReason("Messaging blocked");publish("BLOCK_CREATED",row);}}audit("BLOCK_CREATED",u,c.getPost(),c);}
 @Transactional public void report(Long id,String reason){User u=current.verifiedUser();HelpConversation c=requireParticipant(id,u,false);Report report=new Report();report.setPost(c.getPost());report.setReportedByUser(u);report.setReason("__HELP_CHAT__:"+id+":"+(reason==null?"Safety concern":reason.trim()));reports.save(report);}
 @Transactional public List<NotificationResponse> notificationList(){User u=current.verifiedUser();return notifications.findByRecipientIdOrderByCreatedAtDesc(u.getId()).stream().map(NotificationResponse::from).toList();}
 @Transactional public NotificationResponse readNotification(Long id){User u=current.verifiedUser();HelpNotification n=notifications.findById(id).orElseThrow(()->notFound("Notification not found"));if(!n.getRecipient().getId().equals(u.getId()))throw forbidden("Notification not available");n.setRead(true);return NotificationResponse.from(n);}

 private ConversationResponse response(HelpConversation c,User viewer){User o=other(c,viewer);HelpReconnectRequest pending=reconnects.findByConversationIdAndStatus(c.getId(),ReconnectRequestStatus.PENDING).orElse(null);boolean allowed=c.getStatus()==HelpConversationStatus.ENDED_BY_USER&&c.getPost().getStatus()==PostStatus.ACTIVE&&!blocks.blockedEitherWay(viewer.getId(),o.getId())&&pending==null;return new ConversationResponse(c.getId(),c.getPost().getId(),title(c.getPost()),c.getPost().getContent(),c.getPost().getCategory().getName(),c.getPost().getStatus(),o.getId(),o.getFullName(),c.getStatus(),c.getSessionNumber(),c.getActivatedAt(),c.getEndedAt(),c.getEndedBy()==null?null:c.getEndedBy().getId(),c.getEndedBy()==null?null:c.getEndedBy().getFullName(),c.getEndReason(),c.getLastMessageAt(),allowed,pending==null?null:pending.getId(),pending!=null&&pending.getRequestedBy().getId().equals(viewer.getId()));}
 private MyHelpPostResponse myPost(Post p,Instant closed){Instant ended=closed==null?p.getClosedAt():closed;long helperCount=conversations.countByPostId(p.getId());long pendingVolunteerCount=notifications.countByPostIdAndTypeAndReadFalse(p.getId(),HelpNotificationType.VOLUNTEER_REQUEST);boolean expanded=audits.findFirstByPostIdAndEventTypeOrderByCreatedAtDesc(p.getId(),"HELP_REQUEST_EXPANDED").isPresent();boolean canRequestAll=p.getStatus()==PostStatus.ACTIVE&&!expanded&&helperCount==0&&pendingVolunteerCount==0;return new MyHelpPostResponse(p.getId(),title(p),p.getContent(),p.getCategory().getId(),p.getCategory().getName(),p.getStatus(),p.getCreatedAt(),ended,helperCount,conversations.countByPostIdAndStatus(p.getId(),HelpConversationStatus.ACTIVE),pendingVolunteerCount,expanded,canRequestAll);}
 private VolunteerRequestResponse volunteerResponse(HelpNotification request,User helper,String status,Long conversationId,Instant respondedAt){return new VolunteerRequestResponse(request.getId(),request.getPost().getId(),title(request.getPost()),helper.getId(),helper.getFullName(),request.getRecipient().getId(),status,conversationId,request.getCreatedAt(),respondedAt);}
 private User volunteerUser(HelpNotification request){String[] parts=request.getDedupeKey().split(":");if(parts.length!=3||!"volunteer".equals(parts[0]))throw bad("Volunteer request is invalid");try{return users.findById(Long.parseLong(parts[2])).orElseThrow(()->notFound("Volunteer not found"));}catch(NumberFormatException e){throw bad("Volunteer request is invalid");}}
 private HelpConversation requireParticipant(Long id,User u,boolean lock){HelpConversation c=(lock?conversations.findLockedById(id):conversations.findById(id)).orElseThrow(()->notFound("Conversation not found"));if(!c.getRequester().getId().equals(u.getId())&&!c.getHelper().getId().equals(u.getId()))throw forbidden("You are not a participant in this conversation");return c;}
 private User other(HelpConversation c,User u){return c.getRequester().getId().equals(u.getId())?c.getHelper():c.getRequester();}
 private void requireOpen(Post p){if(p.getStatus()!=PostStatus.ACTIVE)throw new ResponseStatusException(HttpStatus.GONE,"This help request is no longer active");}
 private void requireActive(User u){if(u.getStatus()!=UserStatus.VERIFIED)throw forbidden("Messaging is unavailable for this account");}
 private void requireNotBlocked(User a,User b){if(blocks.blockedEitherWay(a.getId(),b.getId()))throw forbidden("Messaging is unavailable between these members");}
 private void cancelPending(HelpConversation c){reconnects.findByConversationIdAndStatus(c.getId(),ReconnectRequestStatus.PENDING).ifPresent(r->{r.setStatus(ReconnectRequestStatus.CANCELLED);r.setRespondedAt(Instant.now());});}
 private void notify(User to,HelpNotificationType type,Post p,HelpConversation c,String title,String body,String key){if(notifications.existsByDedupeKey(key))return;HelpNotification n=new HelpNotification();n.setRecipient(to);n.setType(type);n.setPost(p);n.setConversation(c);n.setTitle(title);n.setBody(body);n.setDedupeKey(key);notifications.save(n);}
 private void audit(String type,User actor,Post p,HelpConversation c){HelpAuditEvent a=new HelpAuditEvent();a.setEventType(type);a.setActor(actor);a.setPost(p);a.setConversation(c);audits.save(a);}
 private boolean relevant(User u,Post p){String category=p.getCategory().getName().toLowerCase();String fields=String.join(" ",u.getHelpFields().stream().map(ExpertiseField::getName).toList()).toLowerCase();if(category.contains("health"))return fields.contains("medicine")||fields.contains("health");if(category.contains("business"))return fields.contains("business");if(category.contains("job"))return List.of("education","engineering","business","government","upsc","law","judiciary").stream().anyMatch(fields::contains);return fields.contains("community")||fields.contains("government")||fields.contains("law");}
 private String title(Post p){return com.sc.community.dto.HelpChatDtos.title(p);}
 private void publish(String type,HelpConversation c){afterCommit(()->{socket.convertAndSend("/topic/help/"+c.getRequester().getId(),new LifecycleEvent(type,c.getId(),c.getPost().getId()));socket.convertAndSend("/topic/help/"+c.getHelper().getId(),new LifecycleEvent(type,c.getId(),c.getPost().getId()));});}
 private void publishUser(String type,Long userId,Long postId){afterCommit(()->socket.convertAndSend("/topic/help/"+userId,new LifecycleEvent(type,null,postId)));}
 private void publishPost(String type,Long postId){afterCommit(()->socket.convertAndSend("/topic/feed",new com.sc.community.dto.PostDtos.FeedEvent(type,postId)));}
 private void afterCommit(Runnable action){if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){action.run();}});else action.run();}
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException forbidden(String m){return new ResponseStatusException(HttpStatus.FORBIDDEN,m);}private ResponseStatusException notFound(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
}
