BEGIN;

ALTER TABLE posts ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS closed_by_user_id BIGINT REFERENCES users(id);

CREATE TABLE IF NOT EXISTS help_conversations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 post_id BIGINT NOT NULL REFERENCES posts(id), requester_user_id BIGINT NOT NULL REFERENCES users(id), helper_user_id BIGINT NOT NULL REFERENCES users(id),
 status VARCHAR(40) NOT NULL, session_number INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL, activated_at TIMESTAMPTZ NOT NULL,
 ended_at TIMESTAMPTZ, ended_by_user_id BIGINT REFERENCES users(id), end_reason VARCHAR(240), last_message_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uk_help_conversation_post_helper UNIQUE(post_id,helper_user_id), CONSTRAINT ck_help_distinct_users CHECK(requester_user_id<>helper_user_id)
);
CREATE TABLE IF NOT EXISTS help_messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id BIGINT NOT NULL REFERENCES help_conversations(id), sender_id BIGINT NOT NULL REFERENCES users(id),
 message_body TEXT NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS help_reconnect_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id BIGINT NOT NULL REFERENCES help_conversations(id), requested_by_user_id BIGINT NOT NULL REFERENCES users(id),
 requested_to_user_id BIGINT NOT NULL REFERENCES users(id), status VARCHAR(24) NOT NULL, created_at TIMESTAMPTZ NOT NULL, responded_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS user_blocks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, blocker_user_id BIGINT NOT NULL REFERENCES users(id), blocked_user_id BIGINT NOT NULL REFERENCES users(id),
 created_at TIMESTAMPTZ NOT NULL, CONSTRAINT uk_user_block_pair UNIQUE(blocker_user_id,blocked_user_id), CONSTRAINT ck_block_distinct_users CHECK(blocker_user_id<>blocked_user_id)
);
CREATE TABLE IF NOT EXISTS help_notifications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, recipient_user_id BIGINT NOT NULL REFERENCES users(id), type VARCHAR(40) NOT NULL,
 post_id BIGINT REFERENCES posts(id), conversation_id BIGINT REFERENCES help_conversations(id), title VARCHAR(180) NOT NULL, body VARCHAR(500) NOT NULL,
 dedupe_key VARCHAR(180) NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL, CONSTRAINT uk_help_notification_dedupe UNIQUE(dedupe_key)
);
CREATE TABLE IF NOT EXISTS help_audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type VARCHAR(40) NOT NULL, actor_user_id BIGINT REFERENCES users(id), post_id BIGINT REFERENCES posts(id),
 conversation_id BIGINT REFERENCES help_conversations(id), created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_help_conversation_post_status ON help_conversations(post_id,status);
CREATE INDEX IF NOT EXISTS idx_help_conversation_requester_status ON help_conversations(requester_user_id,status);
CREATE INDEX IF NOT EXISTS idx_help_conversation_helper_status ON help_conversations(helper_user_id,status);
CREATE INDEX IF NOT EXISTS idx_help_message_conversation_created ON help_messages(conversation_id,created_at);
CREATE INDEX IF NOT EXISTS idx_help_reconnect_conversation_status ON help_reconnect_requests(conversation_id,status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_help_reconnect_pending ON help_reconnect_requests(conversation_id) WHERE status='PENDING';
CREATE INDEX IF NOT EXISTS idx_help_notification_recipient_read ON help_notifications(recipient_user_id,is_read,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_active_category ON posts(status,category_id);
COMMIT;
