package com.sc.community.service;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.sc.community.dto.HelpChatDtos.ConversationResponse; import com.sc.community.entity.*; import com.sc.community.repository.*; import java.time.*; import java.util.*;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.http.HttpStatus; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.web.server.ResponseStatusException;

@ExtendWith(MockitoExtension.class)
class HelpChatServiceTest{
 @Mock PostRepository posts;@Mock HelpConversationRepository conversations;@Mock HelpMessageRepository messages;@Mock HelpReconnectRequestRepository reconnects;@Mock UserBlockRepository blocks;@Mock HelpNotificationRepository notifications;@Mock HelpVolunteerRequestRepository volunteers;@Mock HelpAuditEventRepository audits;@Mock UserRepository users;@Mock ReportRepository reports;@Mock CurrentUserService current;@Mock DirectoryService directory;@Mock SimpMessagingTemplate socket;
 HelpChatService service;User ravi,anita,sandeep;Post post;HelpConversation anitaChat,sandeepChat;
 @BeforeEach void setup(){service=new HelpChatService(posts,conversations,messages,reconnects,blocks,notifications,volunteers,audits,users,reports,current,directory,socket);ravi=user(1,"Ravi");anita=user(2,"Anita");sandeep=user(3,"Sandeep");Category category=new Category();category.setId(4L);category.setName("Education Help");post=new Post();post.setId(10L);post.setUser(ravi);post.setCategory(category);post.setContent("Child school admission guidance");post.setStatus(PostStatus.ACTIVE);post.setCreatedAt(Instant.now());anitaChat=chat(91,anita);sandeepChat=chat(92,sandeep);lenient().when(blocks.blockedEitherWay(anyLong(),anyLong())).thenReturn(false);lenient().when(reconnects.findByConversationIdAndStatus(anyLong(),eq(ReconnectRequestStatus.PENDING))).thenReturn(Optional.empty());lenient().when(volunteers.countByPostIdAndStatus(anyLong(),eq(VolunteerRequestStatus.PENDING))).thenReturn(0L);lenient().when(notifications.existsByDedupeKey(anyString())).thenReturn(false);lenient().when(notifications.save(any())).thenAnswer(i->i.getArgument(0));lenient().when(audits.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void separateHelpersCreateIndependentChats(){when(current.verifiedUser()).thenReturn(anita,sandeep);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findByPostIdAndHelperId(eq(10L),anyLong())).thenReturn(Optional.empty());when(conversations.saveAndFlush(any())).thenAnswer(i->{HelpConversation c=i.getArgument(0);c.setId(c.getHelper().getId()+100);return c;});assertThat(service.offer(10L).otherUserName()).isEqualTo("Ravi");assertThat(service.offer(10L).id()).isEqualTo(103L);verify(conversations,times(2)).saveAndFlush(any());}
 @Test void eitherParticipantEndsOnlySelectedChat(){when(current.verifiedUser()).thenReturn(ravi);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));service.end(91L,"");assertThat(anitaChat.getStatus()).isEqualTo(HelpConversationStatus.ENDED_BY_USER);assertThat(sandeepChat.getStatus()).isEqualTo(HelpConversationStatus.ACTIVE);assertThat(anitaChat.getEndedBy()).isEqualTo(ravi);}
 @Test void nonParticipantCannotEnd(){User outsider=user(9,"Outsider");when(current.verifiedUser()).thenReturn(outsider);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));assertThatThrownBy(()->service.end(91L,null)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN));}
 @Test void reconnectNeedsAcceptance(){anitaChat.setStatus(HelpConversationStatus.ENDED_BY_USER);when(current.verifiedUser()).thenReturn(ravi,anita);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));when(reconnects.findFirstByConversationIdOrderByCreatedAtDesc(91L)).thenReturn(Optional.empty());when(reconnects.saveAndFlush(any())).thenAnswer(i->{HelpReconnectRequest r=i.getArgument(0);r.setId(51L);return r;});var requested=service.requestReconnect(91L);assertThat(anitaChat.getStatus()).isEqualTo(HelpConversationStatus.ENDED_BY_USER);HelpReconnectRequest request=new HelpReconnectRequest();request.setId(51L);request.setConversation(anitaChat);request.setRequestedBy(ravi);request.setRequestedTo(anita);request.setStatus(ReconnectRequestStatus.PENDING);when(reconnects.findById(51L)).thenReturn(Optional.of(request));when(reconnects.findLockedById(51L)).thenReturn(Optional.of(request));service.decide(51L,true);assertThat(anitaChat.getStatus()).isEqualTo(HelpConversationStatus.ACTIVE);assertThat(anitaChat.getSessionNumber()).isEqualTo(2);assertThat(requested.status()).isEqualTo(ReconnectRequestStatus.PENDING);}
 @Test void duplicateReconnectIsRejected(){anitaChat.setStatus(HelpConversationStatus.ENDED_BY_USER);HelpReconnectRequest pending=new HelpReconnectRequest();when(current.verifiedUser()).thenReturn(ravi);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));when(reconnects.findByConversationIdAndStatus(91L,ReconnectRequestStatus.PENDING)).thenReturn(Optional.of(pending));assertThatThrownBy(()->service.requestReconnect(91L)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.CONFLICT));}
 @Test void closingPostEndsAllActiveChatsAndCancelsReconnects(){when(current.verifiedUser()).thenReturn(ravi);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.lockByPostAndStatus(10L,HelpConversationStatus.ACTIVE)).thenReturn(List.of(anitaChat,sandeepChat));HelpReconnectRequest pending=new HelpReconnectRequest();pending.setStatus(ReconnectRequestStatus.PENDING);when(reconnects.findByConversationPostIdAndStatus(10L,ReconnectRequestStatus.PENDING)).thenReturn(List.of(pending));when(conversations.countByPostId(10L)).thenReturn(2L);service.closePost(10L);assertThat(post.getStatus()).isEqualTo(PostStatus.CLOSED);assertThat(anitaChat.getStatus()).isEqualTo(HelpConversationStatus.ENDED_POST_CLOSED);assertThat(sandeepChat.getStatus()).isEqualTo(HelpConversationStatus.ENDED_POST_CLOSED);assertThat(pending.getStatus()).isEqualTo(ReconnectRequestStatus.CANCELLED);}
 @Test void messageFailsAfterConversationEnd(){anitaChat.setStatus(HelpConversationStatus.ENDED_BY_USER);when(current.verifiedUser()).thenReturn(ravi);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));assertThatThrownBy(()->service.send(91L,"hello")).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN));verify(messages,never()).save(any());}
 @Test void messageAndReconnectFailAfterPostClose(){post.setStatus(PostStatus.CLOSED);anitaChat.setStatus(HelpConversationStatus.ENDED_POST_CLOSED);when(current.verifiedUser()).thenReturn(ravi);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));assertThatThrownBy(()->service.send(91L,"hello")).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.GONE));assertThatThrownBy(()->service.requestReconnect(91L)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.GONE));}
 @Test void reconnectDeclineKeepsConversationEnded(){anitaChat.setStatus(HelpConversationStatus.ENDED_BY_USER);HelpReconnectRequest request=reconnect(51L);when(current.verifiedUser()).thenReturn(anita);when(reconnects.findById(51L)).thenReturn(Optional.of(request));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(reconnects.findLockedById(51L)).thenReturn(Optional.of(request));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));service.decide(51L,false);assertThat(request.getStatus()).isEqualTo(ReconnectRequestStatus.DECLINED);assertThat(anitaChat.getStatus()).isEqualTo(HelpConversationStatus.ENDED_BY_USER);assertThat(request.getRespondedAt()).isNotNull();}
 @Test void blockOverridesActiveChatAndCancelsReconnect(){HelpReconnectRequest pending=reconnect(51L);when(current.verifiedUser()).thenReturn(ravi);when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));when(conversations.between(1L,2L)).thenReturn(List.of(anitaChat));when(reconnects.findByConversationIdAndStatus(91L,ReconnectRequestStatus.PENDING)).thenReturn(Optional.of(pending));when(blocks.findByBlockerIdAndBlockedId(1L,2L)).thenReturn(Optional.empty());service.block(91L);assertThat(anitaChat.getStatus()).isEqualTo(HelpConversationStatus.BLOCKED);assertThat(pending.getStatus()).isEqualTo(ReconnectRequestStatus.CANCELLED);verify(blocks).save(any(UserBlock.class));}
 @Test void closedPostRejectsOldHelpOffer(){post.setStatus(PostStatus.CLOSED);when(current.verifiedUser()).thenReturn(anita);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));assertThatThrownBy(()->service.offer(10L)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.GONE));verify(conversations,never()).saveAndFlush(any());}
 @Test void duplicateHelpOfferDoesNotCreateAnotherConversation(){when(current.verifiedUser()).thenReturn(anita);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findByPostIdAndHelperId(10L,2L)).thenReturn(Optional.of(anitaChat));assertThat(service.offer(10L).id()).isEqualTo(91L);verify(conversations,never()).saveAndFlush(any());}
 @Test void volunteerWaitsForOwnerBeforeOpeningChat(){when(current.verifiedUser()).thenReturn(anita);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findByPostIdAndHelperId(10L,2L)).thenReturn(Optional.empty());when(volunteers.findByPostIdAndVolunteerIdAndStatus(10L,2L,VolunteerRequestStatus.PENDING)).thenReturn(Optional.empty());when(volunteers.saveAndFlush(any())).thenAnswer(i->{HelpVolunteerRequest r=i.getArgument(0);r.setId(61L);return r;});var result=service.volunteer(10L);assertThat(result.status()).isEqualTo(VolunteerRequestStatus.PENDING);verify(conversations,never()).saveAndFlush(any());verify(notifications).save(argThat(n->n.getType()==HelpNotificationType.VOLUNTEER_REQUEST&&n.getRecipient()==ravi));}
 @Test void ownerAcceptingVolunteerCreatesNormalActiveConversation(){HelpVolunteerRequest request=volunteerRequest(61L);when(current.verifiedUser()).thenReturn(ravi);when(volunteers.findById(61L)).thenReturn(Optional.of(request));when(volunteers.findLockedById(61L)).thenReturn(Optional.of(request));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findByPostIdAndHelperId(10L,2L)).thenReturn(Optional.empty());when(conversations.saveAndFlush(any())).thenAnswer(i->{HelpConversation c=i.getArgument(0);c.setId(101L);return c;});var result=service.decideVolunteer(61L,true);assertThat(result.status()).isEqualTo(VolunteerRequestStatus.ACCEPTED);assertThat(result.conversationId()).isEqualTo(101L);assertThat(request.getConversation().getStatus()).isEqualTo(HelpConversationStatus.ACTIVE);}
 @Test void unrelatedMemberCannotAcceptVolunteerRequest(){HelpVolunteerRequest request=volunteerRequest(61L);when(current.verifiedUser()).thenReturn(sandeep);when(volunteers.findById(61L)).thenReturn(Optional.of(request));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(volunteers.findLockedById(61L)).thenReturn(Optional.of(request));assertThatThrownBy(()->service.decideVolunteer(61L,true)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN));verify(conversations,never()).saveAndFlush(any());}
 @Test void requestToAllNotifiesEveryVerifiedNonAdminWhenNoResponse(){when(current.verifiedUser()).thenReturn(ravi);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.countByPostId(10L)).thenReturn(0L);when(users.findByStatus(UserStatus.VERIFIED)).thenReturn(List.of(ravi,anita,sandeep));var result=service.requestAll(10L);assertThat(result.audienceExpanded()).isTrue();assertThat(result.canRequestAll()).isFalse();verify(notifications,times(2)).save(argThat(n->n.getType()==HelpNotificationType.HELP_REQUEST_EXPANDED));}
 @Test void requestToAllIsRejectedAfterDirectHelpResponse(){when(current.verifiedUser()).thenReturn(ravi);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.countByPostId(10L)).thenReturn(1L);assertThatThrownBy(()->service.requestAll(10L)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.CONFLICT));verify(users,never()).findByStatus(any());}
 @Test void activeAndHistoryAreFilteredByBackendQueries(){anitaChat.setStatus(HelpConversationStatus.ENDED_BY_USER);when(current.verifiedUser()).thenReturn(ravi);when(conversations.forUserByStatus(1L,HelpConversationStatus.ACTIVE)).thenReturn(List.of(sandeepChat));when(conversations.history(1L)).thenReturn(List.of(anitaChat));assertThat(service.list("ACTIVE")).extracting(ConversationResponse::id).containsExactly(92L);assertThat(service.list("HISTORY")).extracting(ConversationResponse::id).containsExactly(91L);}
 @Test void nonOwnerCannotClosePost(){when(current.verifiedUser()).thenReturn(anita);when(posts.findLockedById(10L)).thenReturn(Optional.of(post));assertThatThrownBy(()->service.closePost(10L)).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN));assertThat(post.getStatus()).isEqualTo(PostStatus.ACTIVE);verify(conversations,never()).lockByPostAndStatus(anyLong(),any());}
 @Test void messageLocksPostBeforeConversationMutation(){when(current.verifiedUser()).thenReturn(ravi);when(conversations.findById(91L)).thenReturn(Optional.of(anitaChat));when(posts.findLockedById(10L)).thenReturn(Optional.of(post));when(conversations.findLockedById(91L)).thenReturn(Optional.of(anitaChat));when(messages.save(any())).thenAnswer(i->{HelpMessage m=i.getArgument(0);m.setId(81L);m.setCreatedAt(Instant.now());return m;});service.send(91L,"hello");InOrder order=inOrder(posts,conversations,messages);order.verify(posts).findLockedById(10L);order.verify(conversations).findLockedById(91L);order.verify(messages).save(any());}
 private HelpReconnectRequest reconnect(long id){HelpReconnectRequest r=new HelpReconnectRequest();r.setId(id);r.setConversation(anitaChat);r.setRequestedBy(ravi);r.setRequestedTo(anita);r.setStatus(ReconnectRequestStatus.PENDING);return r;}private HelpVolunteerRequest volunteerRequest(long id){HelpVolunteerRequest r=new HelpVolunteerRequest();r.setId(id);r.setPost(post);r.setVolunteer(anita);r.setRequestedTo(ravi);r.setStatus(VolunteerRequestStatus.PENDING);r.setCreatedAt(Instant.now());return r;}private User user(long id,String name){User u=new User();u.setId(id);u.setFullName(name);u.setEmail(name.toLowerCase()+"@test.local");u.setStatus(UserStatus.VERIFIED);return u;}private HelpConversation chat(long id,User helper){HelpConversation c=new HelpConversation();c.setId(id);c.setPost(post);c.setRequester(ravi);c.setHelper(helper);c.setStatus(HelpConversationStatus.ACTIVE);c.setSessionNumber(1);c.setActivatedAt(Instant.now());return c;}
}
