package com.sc.community.entity;
public enum HelpNotificationType { NEW_HELP_POST, HELP_OFFER_RECEIVED, NEW_HELP_MESSAGE, CONVERSATION_ENDED, RECONNECT_REQUEST, RECONNECT_ACCEPTED, RECONNECT_DECLINED, POST_CLOSED }
